name: Deploy to Hostinger

on:
  push:
    branches: [ main, hostinger-deployment ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build frontend
      run: npm run build
      env:
        NODE_ENV: production
    
    - name: Deploy to Hostinger via SSH
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.SSH_HOST }}
        REMOTE_USER: ${{ secrets.SSH_USERNAME }}
        REMOTE_PORT: ${{ secrets.SSH_PORT }}
        SOURCE: "dist/"
        TARGET: ${{ secrets.SSH_TARGET_DIR }}
        EXCLUDE: "/node_modules/, /.git/, /.github/, /.env"
        SCRIPT_BEFORE: |
          whoami
          ls -al
        SCRIPT_AFTER: |
          echo "Deployment completed successfully!"
          cd ${{ secrets.SSH_TARGET_DIR }}
          ls -al